version: "3"
services:
    postgres:
      image: postgres:latest
      container_name: kafka_postgres_container
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: password
        POSTGRES_DB: coordonnee
    