version: '3'

services:
  api:
    build: ./api
    image: kafka_api
    container_name: kafka_api_container
    ports:
        - "3001:3001"
    volumes:
        - ./api:/app
    command: npm start
    depends_on:
        - postgres
    networks:
      - archimicroprojet_kafka_net

  kafka-consumer:
    build:
      context: ./backend/consumer
    environment:
      KAFKA_BROKER: kafka-broker:29092
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coordonnee
    networks:
      - archimicroprojet_kafka_net

networks:
  archimicroprojet_kafka_net:
    external: true
