version: '3'

services:
  api:
    build: ./api
    image: kafka_api
    container_name: kafka_api_container
    ports:
        - "3001:3001"
    volumes:
        - ./api:/app
    command: npm start
    depends_on:
        - postgres