version: '3'

services:
  kafka-producer-ip1:
    build:
      context: ./path/to/producer-ip1
    environment:
      KAFKA_BROKER: kafka-broker:9092

  kafka-producer-ip2:
    build:
      context: ./path/to/producer-ip2
    environment:
      KAFKA_BROKER: kafka-broker:9092

networks:
  default:
    external:
      name: kafka_net
