version: '3'

services:
  kafka-producer:
    build:
      context: ./backend/producer
    environment:
      KAFKA_BROKER: kafka-broker:9092
    networks:
      - kafka_net

networks:
  kafka_net:
    external: true
