version: '3'

services:


  kafka-consumer:
    build:
      context: ./
    environment:
      KAFKA_BROKER: kafka:9092 #change to 29092 when testing with diff pc
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coordonnee
    networks:
      - archimicroprojet_kafka_net
    
  
 


networks:
  archimicroprojet_kafka_net:
    external: true
