version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coordonnee
    volumes:
      - ./db_mivroarchie.dump:/app/db_mivroarchie.dump
